defaults:
  - data: ptbxl
  - model: simple
  - task: superclass
  - trainer: default
  - _self_

seed: 42
device: cuda

wandb:
  enabled: true
  project: deep-ecg
  group: sanity
  name: null
  tags: []
  notes: ""

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
